# Generated by Django 3.2.14 on 2022-07-13 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_product_manufacturer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='manufacturer',
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.ManyToManyField(to='core.Manufacturer'),
        ),
    ]
