# Generated by Django 3.2.13 on 2022-06-23 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='avalability',
            new_name='availability',
        ),
    ]
