# Generated by Django 3.2.13 on 2022-06-24 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_avalability_product_availability'),
    ]

    operations = [
        migrations.RenameField(
            model_name='size',
            old_name='size',
            new_name='name',
        ),
    ]
